[package]
name = "saya"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Settlement service for Katana."

[dependencies]
# saya
saya-core.workspace = true

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
starknet-types-core.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
url.workspace = true
log.workspace = true
